### ISSUE TITLE
Поменять формат хранения терминов с JSON на YAML

### ISSUE THREAD

**Issue by sashachabin** [ariarzer/css-dictionaly#2]
Предлагаю преобразовать JSON в YAML, который кажется более лаконичным, чем JSON

Аргументы:
- Чуть короче, особенно заметно при большой вложенности
- Поддерживает комментарии
- Часто используется, особенно в конфигах (gihub actions, gitlab ci)
- На GitHub в Markdown часто оказывается подобный синтаксис (см. [таблицу сверху](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md))
 
### JSON
```json
{
  "name_ru": "неопределенный размер",
  "name_eng": "indefinite size",
  "define_ru": "Размер, который не определен. Неопределенное [доступное пространство](/available_space) по существу бесконечно.",
  "define_eng": "A size that is not definite. Indefinite available space is essentially infinite.",
  "tag": "css-box-sizing",
  "link": "https://drafts.csswg.org/css-sizing-3/#indefinite"
}
```

### YAML
```yaml
---
name_ru: неопределенный размер
name_eng: indefinite size
define_ru: Размер, который не определен. Неопределенное [доступное пространство](/available_space)
  по существу бесконечно.
define_eng: A size that is not definite. Indefinite available space is essentially
  infinite.
tag: css-box-sizing
link: https://drafts.csswg.org/css-sizing-3/#indefinite
```

Кажется, что тегов может быть несколько и я бы предложил их собирать в массив, либо назвать это `categories`
```
tags:
- css-box-sizing
- test
```

## Редеринг
- При сборке — yaml ([пример кода](https://eemeli.org/yaml/#yaml-parse))
- На клиенте, если вдруг нужно — js-yaml ([демо](http://nodeca.github.io/js-yaml/))

---

Если идея нравится, то могу сделать:

- [ ] Перенести текущие данные из JSON в YAML
- [ ] При сборке добавить конвертацию YAML в JSON
